create table BaselineCurrentData([Baseline Month] nvarchar(500),
[Employee] nvarchar(500),
[Current Baseline Month] nvarchar(500),
[Position ID] nvarchar(500),
[Employee Status] nvarchar(500),
[EID] nvarchar(500),
[Full Name] nvarchar(500),
[Business  Email Information Email Address] nvarchar(500),
[BU/SSU Description] nvarchar(500),
[LOB/Segment Description] nvarchar(500),
[Vertical Description] nvarchar(500),
[Sub Vertical Description] nvarchar(500),
[Entity Description] nvarchar(500),
[Reporting Manager User Sys ID] nvarchar(500),
[Cost Center Description] nvarchar(500),
[International Region] nvarchar(500),
[Facility  Country] nvarchar(500),
[Facility  Description] nvarchar(500),
[Band/Sub Band  Description] nvarchar(500),
[Job Level] nvarchar(500),
[Designation Desc] nvarchar(500),
[Title] nvarchar(500),
[Employment Details Tata Group Joining Date] nvarchar(500),
[Employment Details Hire Date] nvarchar(500),
[Employment Details Last Working Date] nvarchar(500),
[Employment Details Termination Date] nvarchar(500),
[Event] nvarchar(500),
[Event Reason] nvarchar(500),
[Employee Type] nvarchar(500),
[Employee Class] nvarchar(500),
[Job Family Description] nvarchar(500),
[Internal Specialization Name] nvarchar(500),
[Job Code] nvarchar(500),
[Job Code Description] nvarchar(500),
[Variable Pay Plan Type] nvarchar(500),
[CTC-Currency] nvarchar(500),
[FIXPAY-Amount] nvarchar(500),
[RETIRALS-Amount] nvarchar(500),
[VARPAY-Amount] nvarchar(500),
[OTE-Amount] nvarchar(500),
[AnnualFringe-Amount] nvarchar(500),
[CTC-Amount] nvarchar(500),
[Benefits in Local Currency (From Master)] nvarchar(500),
[Loaded Cost in Local Currency] nvarchar(500),
[OTE (US $)] nvarchar(500),
[Benefits US $ (From Master)] nvarchar(500),
[AID] nvarchar(500),
[Reporting Manager] nvarchar(500),
[Gender] nvarchar(500),
[Account ID] nvarchar(500),
[BU/SSU Code] nvarchar(500),
[LOB/Segment Code] nvarchar(500),
[Vertical Code] nvarchar(500),
[Sub Vertical Code] nvarchar(500),
[Cost Center Code] nvarchar(500),
[Geozone  Geo Zone Name] nvarchar(500),
[Geozone  Geo Zone ID] nvarchar(500),
[Entity Code] nvarchar(500),
[CTC with Different Exchange Rates] nvarchar(500),
[B-Headcount Count] nvarchar(500),
[Counts] nvarchar(500),
[Start Date-From Master] nvarchar(500),
[End Date-From Master] nvarchar(500),
[Vertical Text] nvarchar(500),
[BU Code] nvarchar(500),
[Finance Function corresponding to BU] nvarchar(500)
)

BULK INSERT [dbo].BaselineCurrentData 
   FROM 'C:\Users\msazureuser\Desktop\Anaplan\Anaplan 2018\AutomateProcess\BaselineCurrentData.txt'  
   WITH   
      (  
		
	     FIELDTERMINATOR='\t',  
         ROWTERMINATOR ='\n' 
		 ,Firstrow =2
      );
