create table sim(
[a] nvarchar(500),
[b] nvarchar(500),
[YTD - AOP] nvarchar(500),
[ANA_ID] nvarchar(500),
[Anaplan Code] nvarchar(500),
[Position ID] nvarchar(500),
[Parent Position Position ID] nvarchar(500),
[Par Pos] nvarchar(500),
[Planned Yet Open] nvarchar(500),
[Cost Center] nvarchar(500),
[BU/SSU (Label)] nvarchar(500),
[LOB / Segment] nvarchar(500),
[Vertical (Label)] nvarchar(500),
[Sub Vertical (Label)] nvarchar(500),
[Entity] nvarchar(500),
[Job Family] nvarchar(500),
[Job Family Cluster] nvarchar(500),
[Job Family Cluster Count] nvarchar(500),
[Job Family Cluster Cost] nvarchar(500),
[Bonus Plan Name] nvarchar(500),
[Variable Pay Plan Type] nvarchar(500),
[Currency] nvarchar(500),
[Budgeted Allowance] nvarchar(500),
[Budgeted Base] nvarchar(500),
[Budgeted Benefits] nvarchar(500),
[Budgeted OTE] nvarchar(500),
[Budgeted Retirals] nvarchar(500),
[Budgeted Variable] nvarchar(500),
[Budgeted Loaded Cost] nvarchar(500),
[Budgeted Loaded Cost USD] nvarchar(500),
[Prorated Budgeted Cost] nvarchar(500),
[Country] nvarchar(500),
[Employee Sub Band] nvarchar(500),
[jobLevel (Picklist Label)] nvarchar(500),
[Designation] nvarchar(500),
[Career Path] nvarchar(500),
[Internal Specialisation] nvarchar(500),
[Effective Date] nvarchar(500),
[Employee Type (Picklist Label)] nvarchar(500),
[Geozone (Geo Zone Name)] nvarchar(500),
[Facility  Description] nvarchar(500),
[jobCode (Label)] nvarchar(500),
[Is Growth Business?] nvarchar(500),
[Position Start Date] nvarchar(500),
[Position End Date] nvarchar(500),
[AOP Budgeted Position?] nvarchar(500),
[AOP Prorated Cost] nvarchar(500),
[AOP Budgeted Country] nvarchar(500),
[PositionTitle] nvarchar(500),
[effectiveStatus] nvarchar(500),
[FTE] nvarchar(500),
[BU/SSU (BU / SSU) Code] nvarchar(500),
[LOB/Segment (LOB / Segment )] nvarchar(500),
[Vertical (Vertical Code)] nvarchar(500),
[Sub Vertical (Sub Vertical)] nvarchar(500),
[Legal Entity (Entity)] nvarchar(500),
[TA Lead] nvarchar(500),
[TA Lead (First Name)] nvarchar(500),
[TA Lead (Last Name)] nvarchar(500),
[BU HR (Position ID)] nvarchar(500),
[mdfSystemRecordStatus] nvarchar(500),
[Strategy 2.0] nvarchar(500),
[Custom 1] nvarchar(500),
[Custom 2] nvarchar(500),
[Employee Class (Picklist Label)] nvarchar(500),
[HC_MTD] nvarchar(500),
[Band/Sub Band] nvarchar(500),
[MTD Cost Local Currency] nvarchar(500),
[MTD Cost] nvarchar(500),
[EMP] nvarchar(500),
[PID_TEXT] nvarchar(500),
[Used Positions] nvarchar(500),
[Exist in HC] nvarchar(500),
[Exist in TA (Open and Close)] nvarchar(500),
[Exist in TA (Offered)] nvarchar(500),
[AID] nvarchar(500),
[JID] nvarchar(500),
[Start Date Balance AOP] nvarchar(500),
[BALANCE AOP] nvarchar(500),
[DISPLAY IN AOP] nvarchar(500),
[DISPLAY IN SIMULATION] nvarchar(500),
[Headcount-AOP] nvarchar(500),
[AOP Exit HC] nvarchar(500),
[AOP Exit CTC] nvarchar(500),
[YTD AOP Exit HC] nvarchar(500),
[YTD AOP Exit Cost] nvarchar(500),
[HC Exit] nvarchar(500),
[LC Exit] nvarchar(500),
[LC-Exit] nvarchar(500),
[HC-Exit] nvarchar(500),
[Parent Country] nvarchar(500),
[Country For Outlook] nvarchar(500),
[HC INDIA OUTLOOK] nvarchar(500),
[COST INDIA OUTLOOK] nvarchar(500),
[HC INT. OUTLOOK] nvarchar(500),
[COST INT. OUTLOOK] nvarchar(500),
[AOP Budgeted Currency] nvarchar(500),
[AOP Budgeted Sub Band] nvarchar(500),
[cURRENT MONTH] nvarchar(500),
[Month Period] nvarchar(500),
[Start. 2.0 check] nvarchar(500),
[Counts Stra. 2.0] nvarchar(500),
[Previous Sub Band] nvarchar(500),
[Manager ID] nvarchar(500),
[Annualized Cost AOP] nvarchar(500),
[test - cost india outlook] nvarchar(500),
[test2] nvarchar(500),
[Cost India outlook - aop budgeted true] nvarchar(500),
[Cost Int. outlook - aop budgeted true] nvarchar(500),
[Month_Number_AOP_budgeted_true] nvarchar(500),
[Monthly HC] nvarchar(500))

BULK INSERT [dbo].sim 
   FROM 'C:\Users\msazureuser\Desktop\Anaplan\Anaplan 2018\AutomateProcess\Simulation_AOP_CY.txt'  
   WITH   
      (  
		
	     FIELDTERMINATOR='\t',  
         ROWTERMINATOR ='\n',
		 Firstrow = 2
      );

