	--drop table map_citycluster_region
	create table map_citycluster_region(region nvarchar(100), city_cluster nvarchar(100))
	insert into map_citycluster_region values('Americas','Other - US')
	insert into map_citycluster_region values('Americas','Other - Canada')
	insert into map_citycluster_region values('Americas','Montreal')
	insert into map_citycluster_region values('Americas','Burlingame')
	insert into map_citycluster_region values('Americas','Herndon')
	insert into map_citycluster_region values('Americas','Home - US')
	insert into map_citycluster_region values('Americas','Matawan')
	insert into map_citycluster_region values('Americas','Santa Clara')
	insert into map_citycluster_region values('APAC','Other - APAC')
	insert into map_citycluster_region values('APAC','Hong Kong')
	insert into map_citycluster_region values('APAC','Singapore')
	insert into map_citycluster_region values('Europe','Other - Europe')
	insert into map_citycluster_region values('Europe','Paris')
	insert into map_citycluster_region values('Europe','Frankfurt')
	insert into map_citycluster_region values('Europe','Madrid')
	insert into map_citycluster_region values('Europe','Home - UK')
	insert into map_citycluster_region values('India','Other - India')
	insert into map_citycluster_region values('India','Bengaluru')
	insert into map_citycluster_region values('India','Chennai')
	insert into map_citycluster_region values('India','Delhi')
	insert into map_citycluster_region values('India','Hyderabad')
	insert into map_citycluster_region values('India','Mumbai')
	insert into map_citycluster_region values('India','Pune')
	insert into map_citycluster_region values('MENA','Other - MENA')
	insert into map_citycluster_region values('MENA','Dubai')
									   